name: Build and Test

on:
  push:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  php:
    name: Build PHP part
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - lowest
          - locked
    steps:
      - name: Checkout source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up PHP
        uses: shivammathur/setup-php@aa1fe473f9c687b6fb896056d771232c0bc41161 # tag=2.19.0
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # renovate: tag=2.1.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
